encoding: utf-8
# Site settings
title: Cannot, today Monday
email: rreedd555@gmail.com
author: tknv
description: NO ROCKS, NO PUNKS, SO SUCKS !
cover: /images/site-cover.jpg
width: 1024
height: 768
location: local
baseurl:     ""
url:         "https://tknv.github.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-2683223-21
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: true
enable_anchorjs: true

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tknvio

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: true
facebook_appid: 352607461750023
facebook_comments_number: 10

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username: tknv
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'fenced_code_blocks', 'footnotes']
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

jekyll-archives:
  enabled:
    - year
    - month
    # - tags
  # layout: 'archive'
  layouts:
    year: year-archive
    month: month-archive
  #   # day: day-archive
  #   tag: tag-archive-layout
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
  #   # day: '/:year/:month/:day/'
  #   tag: '/tag/:name/'
  #   # category: '/category/:name/'
